services:
  test-discovery-service:
    build: ./discovery-service
    container_name: test-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 60s
  test-gateway-service:
    build: ./gateway-service
    container_name: test-gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://test-discovery-service:8761/eureka
    depends_on:
      test-discovery-service:
        condition: service_healthy
  test-film-service:
    build: ./film-service
    container_name: test-film-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - DISCOVERY_SERVICE_URL=http://test-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8081/actuator/health" ]
      interval: 60s
    depends_on:
      test-discovery-service:
        condition: service_healthy
  angular-front-end:
    build: ./capfi-angular-frontend
    container_name: angular-front-end
    ports:
      - '80:80'
    expose:
      - '80'